title: "AI for Management Leaders"
description: "An open-source executive guide to AI strategy, regulation, governance, and risk"

# IMPORTANT:
# If your site URL is https://USER.github.io/REPO then set:
# baseurl: "/REPO"
baseurl: "/AI-for-Leaders"
url: "https://khukt.github.io"

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dark"

search: true
permalink: pretty

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

collections:
  book:
    output: true
    permalink: /book/:name/

defaults:
  - scope:
      path: ""
      type: book
    values:
      layout: single
      sidebar:
        nav: "book"
